name: Create auto Pull Request for branch "homolog"

on:
  push: 
    branches: homolog

jobs:
  createAutoPr:
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v4

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          title: Feature of activate buttons delete and clear all is OK
          body: | # Write Pull Request feature specifications here
           Auto PR for Homolog.
           The user can now delete the last digit entered or clear all text boxes.
          branch: ${{ github.ref }} #The branch where you commit.
          base: main
          assignees: ${{ github.actor }}
          # Write the labels referring to the Pull Request
          labels: |
           New feature
           Buttons is on
           
      - name: Check output
        run: |
          echo "Pull Request Number: ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL: ${{ steps.cpr.outputs.pull-request-url }}"
