name: Create auto Pull Request for branch "homolog"

on:
  push: 
    branches: developer

jobs:
  createAutoPr:
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v4

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          title: "Feature: Calcular values"
          body: | # Write Pull Request feature specifications here
            Auto PR for Homolog.
            Now the user can calcular values in real time or click button of equals for in GUI
          branch: ${{ github.ref }} #The branch where you commit.
          base: homolog
          assignees: ${{ github.actor }}
          # Write the labels referring to the Pull Request
          labels: |
           New feature
           Calcular values
           Button of equals is on

      - name: Check output
        run: |
          echo "Pull Request Number: ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL: ${{ steps.cpr.outputs.pull-request-url }}"
