name: Create auto Pull Request for branch "homolog"

on:
  push: 
    branches: developer

jobs:
  createAutoPr:
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v4

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          title: "Feature: New binary caculator"
          body: | # Write Pull Request feature specifications here
            Auto PR for Homolog.
            Create a manual binary calculator variable, which has the functions of calculating values ​​created in a hard code way and took advantage of and corrected some errors in the automated version.
          branch: ${{ github.ref }} #The branch where you commit.
          base: homolog
          assignees: ${{ github.actor }}
          # Write the labels referring to the Pull Request
          labels: |
           New feature
           New Calc
           Bugfix

      - name: Check output
        run: |
          echo "Pull Request Number: ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL: ${{ steps.cpr.outputs.pull-request-url }}"
