name: Create auto Pull Request for branch "homolog"

on:
  push: 
    branches: homolog

jobs:
  createAutoPr:
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v4

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          title: Aded values for textbox determined and passed for tests in homolog
          body: | # Write Pull Request feature specifications here
           Auto PR for Homolog.
           Now the user can add value in the selected text box by clicking on the buttons.
           User can also alter of text box.
          branch: ${{ github.ref }} #The branch where you commit.
          base: main
          assignees: ${{ github.actor }}
          # Write the labels referring to the Pull Request
          labels: |
           New feature
           Add value
           Alter text box
           Passed for tests

      - name: Check output
        run: |
          echo "Pull Request Number: ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL: ${{ steps.cpr.outputs.pull-request-url }}"
